name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi, thanks for creating your first issue at BlogSite,hope you followed the [code of conduct](https://github.com/ALPHAVIO/BlogSite/blob/master/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md)'
        pr-message: 'Hi, Congratulations for making your first Pull Request at BlogSite!!, Maintainer will review it soon'
